/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_PRINT_H_RPCGEN
#define _RPC_PRINT_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct PrintArgs {
	char *User_name;
	char *Op_name;
	char *File_name;
	char *Time;
};
typedef struct PrintArgs PrintArgs;

#define PRINT_PROG 100471976
#define PRINT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINT_USER_OP 1
extern  enum clnt_stat print_user_op_1(PrintArgs , void *, CLIENT *);
extern  bool_t print_user_op_1_svc(PrintArgs , void *, struct svc_req *);
extern int print_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINT_USER_OP 1
extern  enum clnt_stat print_user_op_1();
extern  bool_t print_user_op_1_svc();
extern int print_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_PrintArgs (XDR *, PrintArgs*);

#else /* K&R C */
extern bool_t xdr_PrintArgs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_PRINT_H_RPCGEN */
