/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_Print.h"

bool_t
xdr_PrintArgs (XDR *xdrs, PrintArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->User_name, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->Op_name, 15))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->File_name, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->Time, 20))
		 return FALSE;
	return TRUE;
}
