/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "RPC_Print.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
print_user_op_1(PrintArgs arg1, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, PRINT_USER_OP,
		(xdrproc_t) xdr_PrintArgs, (caddr_t) &arg1,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}
